### ISSUE TITLE
Redis failing in production for celery jobs

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1297]
After the most recent deployment I get crashes from an "unexpected keyword argument". Haven't changed anything in Redis or the Celery setup. Maybe there's been a redis update breaking things? Will post dump below.

**Comment by mikkonie** [comment]
```
[2021-11-08 17:36:39,125: CRITICAL/MainProcess] Unrecoverable error: TypeError("__init__() got an unexpected keyword argument 'username'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 916, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1065, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 422, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 428, in connection_for_read
    return self.ensure_connected(
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 454, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 382, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 434, in _ensure_connection
    return retry_over_time(
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 878, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 813, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 936, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 918, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 675, in __init__
    self.client.ping()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1106, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1067, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1105, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'username'
```

**Comment by mikkonie** [comment]
mentioned in commit 0f87aa95b961b3f626a7d6a064fdd0d307faf30c

**Comment by mikkonie** [comment]
Upgrading to redis v3.5.3 seems to have fixed this.
