### ISSUE TITLE
Landingzones: Crash on failure on batch checksum validate task

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1307]
This seems similar to #1298 but it happens on a failure. Noticed by Andranik when his landing zone failed. Dump below. Maybe has something to do with the long error message?

**Comment by mikkonie** [comment]
Dump:

```
REDACTED
```

**Comment by mikkonie** [comment]
OK yes, I believe this is because the view tries to shove a string the length of 37k characters into a field where the limit is 1k :P Need to truncate..

**Comment by mikkonie** [comment]
Yep, can reproduce locally:

```
Internal Server Error: /landingzones/taskflow/status/set
Traceback (most recent call last):
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1024)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mikkopen/code/sodar/landingzones/views_taskflow.py", line 262, in post
    zone.set_status(
  File "/home/mikkopen/code/sodar/landingzones/models.py", line 189, in set_status
    self.save()
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(1024)
```

**Comment by mikkonie** [comment]
mentioned in commit d65db3b24ad62d0095aab921c32849febc8099aa

**Comment by mikkonie** [comment]
Fixed!
