### ISSUE TITLE
Landingzones: Inactivezones command crashes if iRODS collection not found

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1311]
Dump below. Should be fixable by simply adding a try-catch and logging the error.

**Comment by mikkonie** [comment]
Dump:

```
Traceback (most recent call last):
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/irods/manager/collection_manager.py", line 17, in get
    result = query.one()
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/irods/query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikkopen/code/sodar/irodsbackend/api.py", line 415, in get_object_stats
    coll = self.irods.collections.get(self._sanitize_coll_path(path))
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/irods/manager/collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/mikkopen/code/sodar/landingzones/management/commands/inactivezones.py", line 55, in handle
    for o in get_output(zones, irods_backend):
  File "/home/mikkopen/code/sodar/landingzones/management/commands/inactivezones.py", line 31, in get_output
    stats = irods_backend.get_object_stats(path)
  File "/home/mikkopen/code/sodar/irodsbackend/api.py", line 417, in get_object_stats
    raise FileNotFoundError('iRODS collection not found')
FileNotFoundError: iRODS collection not found
```

**Comment by mikkonie** [comment]
mentioned in commit 3c2a7b0f6a986d7036dc58666b91eb70b902ba70

**Comment by mikkonie** [comment]
Fixed.
