### ISSUE TITLE
Irodsbackend: Handle unsuccessful iRODS connection gracefully in IrodsStatisticsAjaxView

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1322]
Currently we don't do this. Dump below.

**Comment by mikkonie** [comment]
Dump:

```
Internal Server Error: /irodsbackend/ajax/stats/f6641bb5-6dc2-41c9-8593-bd81a300eae9
Traceback (most recent call last):
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mikkopen/.virtualenvs/sodar/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mikkopen/code/sodar/irodsbackend/views.py", line 102, in dispatch
    and irods_backend.get_path(self.project) not in path
AttributeError: 'NoneType' object has no attribute 'get_path'
```

**Comment by mikkonie** [comment]
mentioned in commit 0ad31dd7e9770296549a2aaf12c519cdd3a6f8a3

**Comment by mikkonie** [comment]
Fixed.
