### ISSUE TITLE
Fix manual building in readthedocs

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1343]
This crashes, dump below. I assume it has something to do with the wrong Django config being used.

**Comment by mikkonie** [comment]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sodar-server/envs/v0.11.0/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/home/docs/checkouts/readthedocs.org/user_builds/sodar-server/envs/v0.11.0/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'
```

**Comment by mikkonie** [comment]
mentioned in commit 5abb6f97a08a17595d62cb247ae981ac988edeec

**Comment by mikkonie** [comment]
Done. Will need to remember to enable the new version when tagging the next release.
