### ISSUE TITLE
Irodsinfo: test_irods_config in permission tests fails in Github CI

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1353]
Works locally. Most likely this is due to irodsbackend not being enabled. Dump below.

```
======================================================================
FAIL: test_irods_config (irodsinfo.tests.test_permissions.TestIrodsinfoPermissions)
Test permissions for IrodsConfigView
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-server/sodar-server/irodsinfo/tests/test_permissions.py", line 35, in test_irods_config
    self.assert_response(url, good_users, 200)
  File "/home/runner/work/sodar-server/sodar-server/src/django-sodar-core/projectroles/tests/test_permissions.py", line 102, in assert_response
    self.assertEqual(response.status_code, status_code, msg=msg)
AssertionError: 302 != 200 : user=superuser
```

**Comment by mikkonie** [comment]
mentioned in commit ae2a88a73dcf0d5ac857a7c9c63c7a0839e2cb34

**Comment by mikkonie** [comment]
Fixed.
