### ISSUE TITLE
Project lock and zone status not handled on network timeout in landing_zone_move

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1532]
(Updated from original ticket)

We have some cases where connections from celery to iRODS time out for some reason within `landing_zone_move`. This will not free the project lock or update the landing zone status.

Example:

```
sodar-celeryd-default_1  | [2023-11-30 10:37:41,753: INFO/MainProcess] Task taskflowbackend.tasks_celery.submit_flow_task[5393f54b-0f52-440c-8453-abe434e06f18] received
sodar-celeryd-default_1  | [2023-11-30 10:37:41,967: INFO/ForkPoolWorker-15] Lock OK for project xxxxx
(...)
sodar-celeryd-default_1  | [2023-11-30 10:40:31,426: CRITICAL/ForkPoolWorker-15] The read operation timed out
sodar-celeryd-default_1  | [2023-11-30 10:40:31,438: ERROR/ForkPoolWorker-15] Could not receive server response
```

A bit later we get:
```
sodar-celeryd-default_1  | [2023-11-30 10:42:31,647: WARNING/ForkPoolWorker-15] Exception ignored in: 
sodar-celeryd-default_1  | [2023-11-30 10:42:31,648: WARNING/ForkPoolWorker-15] <function Connection.__del__ at 0x7f4e7ba76670>
sodar-celeryd-default_1  | [2023-11-30 10:42:31,648: WARNING/ForkPoolWorker-15] Traceback (most recent call last):
sodar-celeryd-default_1  | [2023-11-30 10:42:31,648: WARNING/ForkPoolWorker-15]   File "/usr/local/lib/python3.8/site-packages/irods/connection.py", line 90, in __del__
sodar-celeryd-default_1  | [2023-11-30 10:42:31,649: WARNING/ForkPoolWorker-15]     
sodar-celeryd-default_1  | [2023-11-30 10:42:31,649: WARNING/ForkPoolWorker-15] self.disconnect()
sodar-celeryd-default_1  | [2023-11-30 10:42:31,649: WARNING/ForkPoolWorker-15]   File "/usr/local/lib/python3.8/site-packages/irods/connection.py", line 306, in disconnect
sodar-celeryd-default_1  | [2023-11-30 10:42:31,649: WARNING/ForkPoolWorker-15]     
sodar-celeryd-default_1  | [2023-11-30 10:42:31,650: WARNING/ForkPoolWorker-15] self.socket = self.socket.unwrap()
sodar-celeryd-default_1  | [2023-11-30 10:42:31,650: WARNING/ForkPoolWorker-15]   File "/usr/local/lib/python3.8/ssl.py", line 1285, in unwrap
sodar-celeryd-default_1  | [2023-11-30 10:42:31,651: WARNING/ForkPoolWorker-15]     
sodar-celeryd-default_1  | [2023-11-30 10:42:31,651: WARNING/ForkPoolWorker-15] s = self._sslobj.shutdown()
sodar-celeryd-default_1  | [2023-11-30 10:42:31,651: WARNING/ForkPoolWorker-15] socket
sodar-celeryd-default_1  | [2023-11-30 10:42:31,651: WARNING/ForkPoolWorker-15] .
sodar-celeryd-default_1  | [2023-11-30 10:42:31,651: WARNING/ForkPoolWorker-15] timeout
sodar-celeryd-default_1  | [2023-11-30 10:42:31,652: WARNING/ForkPoolWorker-15] : 
sodar-celeryd-default_1  | [2023-11-30 10:42:31,652: WARNING/ForkPoolWorker-15] The read operation timed out
```

This should be caught and, at the very least, the project lock should be freed.

**Comment by mikkonie** [comment]
Closing, see #1535 and #1537.

**Comment by mikkonie** [comment]
I closed this yesterday but since reconsidered. I should still look into updating the status if we enter a crash like this.

**Comment by mikkonie** [comment]
It turned out my most recent sighting of this was a misunderstanding. A taskflow job was slowed down by external issues, so it appeared to be hanging, while actually still running. Meanwhile, another operation timed out for "natural causes", leading me to confuse the two for eachother. Mental note: learn to read celery logs :)
