### ISSUE TITLE
Docker builds with whitenoise crash from missing select2 file

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1666]
It seems something has been broken in `django-autocomplete-light` and its `select2` dependency, causing whitenoise to fail. The full error can be seen in comments.

[There is some discussion here](https://stackoverflow.com/questions/26829435/collectstatic-command-fails-when-whitenoise-is-enabled) about workaround for these kind of problems.

**Comment by mikkonie** [comment]
Error:
```
Post-processing 'vendor/select2/docs/plugins/highlight/css/brown-paper.css' failed!

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'vendor/select2/docs/plugins/highlight/css/brown-papersq.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ff0f836cfa0>.

The CSS file 'vendor/select2/docs/plugins/highlight/css/brown-paper.css' references a file which could not be found:
  vendor/select2/docs/plugins/highlight/css/brown-papersq.png

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by mikkonie** [comment]
Fixed for now by pinning `django-autocomplete-light==3.9.4`. For future updates, see follow-up in the SODAR Core issue.
