### ISSUE TITLE
Failure in test_import_batch_owl from inaccessible URL

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1694]
It seems some URL we are trying to access has changed.

```
 ======================================================================
ERROR: test_import_batch_owl (ontologyaccess.tests.test_io.TestOBOFormatOntologyIO)
Test importing OWL ontologies in batch (this may take a while)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-server/sodar-server/ontologyaccess/tests/test_io.py", line 105, in test_import_batch_owl
    file = self.obo_io.owl_to_obo(url)
  File "/home/runner/work/sodar-server/sodar-server/ontologyaccess/io.py", line 80, in owl_to_obo
    response = urllib.request.urlopen(owl)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by mikkonie** [comment]
It would appear obolibrary does not like us retrieving ontologies programmatically. It would be possible to fix this by faking the user agent in the request, but they probably wouldn't like that either so we'd better not.

I fixed the immediate bug by removing / commenting out the offending tests. I should still write a new test to import minimal OWL/OMIM files which can be added directly into the repository data, hence this issue remains open for now.
