### ISSUE TITLE
TestProjectZoneView UI test test_zone_locked_superuser() occasionally fails

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1732]
**Edit:** This issue originally contained some other related issues too, but they have been resolved.

The test case `test_zone_locked_superuser()` occasionally fails. This happens mostly in CI, but sometimes in the local dev environment too.

Sadly I haven't so far been able to reproduce it. I've also tried running the test a lot of times with headless mode disabled to see what could be happening, to no avail.

I should maybe also look at the related JQuery to see if something might be going wrong there.

The accompanying test case `test_zone_locked_contributor()`, which works under the exactly same logic, has not failed similarly.

**Comment by mikkonie** [comment]
Forgot to add the dump of the actual test crash, it seems to occur quite frequently.

```
======================================================================
FAIL: test_zone_locked_buttons_superuser (landingzones.tests.test_ui.TestProjectZoneView)
Test ProjectZoneView zone buttons for locked zone as superuser
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-server/sodar-server/landingzones/tests/test_ui.py", line 358, in test_zone_locked_buttons_superuser
    self.assertIsNone(attr)
AssertionError: 'true' is not None
```

**Comment by mikkonie** [comment]
I fixed these issues because I got fed up with the constant CI crashes :)

**Comment by mikkonie** [comment]
Reopening this, as it seems this test can **STILL** crash randomly. I guess my method for fixing it was not foolproof, even though the crashes are noticeably more infrequent now.

```
======================================================================
FAIL: test_zone_locked_superuser (landingzones.tests.test_ui.TestProjectZoneView)
Test ProjectZoneView zone rendering for locked zone as superuser
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-server/sodar-server/landingzones/tests/test_ui.py", line 362, in test_zone_locked_superuser
    self.assertNotIn(
AssertionError: 'disabled' unexpectedly found in 'btn btn-secondary dropdown-toggle sodar-list-dropdown disabled'
```

**Comment by mikkonie** [comment]
I've increased the amount of attempts before we timeout. Let's see if the issue appears again in CI..

**Comment by mikkonie** [comment]
Even after increasing the timeout, the test occasionally fails in CI. I'm starting to think GitHub Actions is just slow. Could also see about updating selenium in the next SODAR Core release.

**Comment by mikkonie** [comment]
Update: Nope, this can also appear in local tests. That is good, since it'll be easier to reproduce and observe with disabled headless mode.

**Comment by mikkonie** [comment]
Closing this issue as it's not up-to-date anymore. Will open a new one to reflect the current issue.

**Comment by mikkonie** [comment]
Looking into this more closely, pretty much the only thing I can think of which can cause the failure is the Ajax call to `CurrentUserRetrieveAPIView`. Maybe that can somehow occasionally fail in the UI test? A quirk in the live server perhaps? We could try retrying the request N times..

**Comment by mikkonie** [comment]
Turns out this is the oldest bug in the dynamic web development book: Calling an async function in otherwise sync code and not waiting for the results. The test is fine, closing this ticket and opening a relevant one.
