### ISSUE TITLE
Editing a comment field with list of strings breaks table rendering

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1790]
It is possible to break the table rendering as follows:

- Edit a comment field with a list of non-ontology string values
- Save edit (regardless of whether anything was actually edited)
- Try to render tables -> render crash

Dump of error and other details in comments.

It seems we are OK with handling comment field values as 1) plain strings, 2) single ontology terms or 3) lists of ontology terms, but not lists of strings.

Also, the problem in fact already stems from the import phase, as we don't internally treat these values as lists when creating the database model.

This should work consistently between all possible value types, or at the very least not crash.

**Comment by mikkonie** [comment]
Dump:
```
Internal Server Error: /samplesheets/ajax/study/tables/e8584f23-c2f6-41ed-9502-3e44cae684cf
Traceback (most recent call last):
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mikkopen/.virtualenvs/sodar14/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mikkopen/code/sodar/samplesheets/views_ajax.py", line 634, in get
    raise ex
  File "/home/mikkopen/code/sodar/samplesheets/views_ajax.py", line 630, in get
    ret_data['tables'] = table_builder.get_study_tables(study)
  File "/home/mikkopen/code/sodar/samplesheets/rendering.py", line 878, in get_study_tables
    study_tables = self.build_study_tables(study, use_config=True)
  File "/home/mikkopen/code/sodar/samplesheets/rendering.py", line 806, in build_study_tables
    ret['study'] = self._build_table(study_refs, node_map, study=study)
  File "/home/mikkopen/code/sodar/samplesheets/rendering.py", line 611, in _build_table
    self._add_ordered_element(node_map[col])
  File "/home/mikkopen/code/sodar/samplesheets/rendering.py", line 319, in _add_ordered_element
    self._add_annotation(
  File "/home/mikkopen/code/sodar/samplesheets/rendering.py", line 410, in _add_annotation
    elif isinstance(ann['value'], dict) or (
TypeError: list indices must be integers or slices, not str
```

**Comment by mikkonie** [comment]
Here's where the conversion happens in the Ajax view.

```
2023-09-12 17:51:28,971 [DEBUG] samplesheets.views: Cell update: {'value': ['P1', 'P2'], 'uuid': '9b509d58-9cec-47c2-ac2a-86b8b204caf1', 'colType': 'CONTACT', 'header_name': 'Performer', 'header_type': 'performer', 'header_field': 'col22', 'obj_cls': 'Process', 'og_value': 'P1; P2'}
```

**Comment by mikkonie** [comment]
Fixed. I failed to decently test this in UI though, because the current test data doesn't include comments fields and editing them on the fly is a pain. I'll add a separate issue for improving test ISA-Tabs.
