### ISSUE TITLE
TypeError raised by Vue app drag select

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1792]
The following error is raised when attempting to "paint" cells:

```
AgGridDragSelect.vue:105 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at VueComponent.isItemSelected (AgGridDragSelect.vue:105:1)
    at eval (AgGridDragSelect.vue:169:1)
    at Array.filter (<anonymous>)
    at VueComponent.onMouseMove (AgGridDragSelect.vue:168:1)
```

This was working in v0.13.4, but currently not. The component itself has not been updated in 10 months, so I suspect a change in the parent component, or maybe some dependency issue..

**Comment by mikkonie** [comment]
Fixed. This was caused by an undocumented breaking change in the base HTML template of SODAR Core v0.13.0. I will back-document that in the next update.
